// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShellApplication.AboutBoxPackage
{
    static class Vsix
    {
        public const string Id = "81d57b07-ce51-4f58-863f-43c40f3e0191";
        public const string Name = "MyIsolatedShell";
        public const string Description = @"Isolated Shell Application with file locator";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Akhil ";
        public const string Tags = "";
    }
}
